//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ServiceConfig {
    
    private double serviceTimeIntervalField;
    
    private ushort mailTriggerField;
    
    private string[] receiversField;
    
    private ServiceConfigWebLinks webLinksField;
    
    /// <remarks/>
    public double ServiceTimeInterval {
        get {
            return this.serviceTimeIntervalField;
        }
        set {
            this.serviceTimeIntervalField = value;
        }
    }
    
    /// <remarks/>
    public ushort MailTrigger {
        get {
            return this.mailTriggerField;
        }
        set {
            this.mailTriggerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Receiver", IsNullable=false)]
    public string[] Receivers {
        get {
            return this.receiversField;
        }
        set {
            this.receiversField = value;
        }
    }
    
    /// <remarks/>
    public ServiceConfigWebLinks WebLinks {
        get {
            return this.webLinksField;
        }
        set {
            this.webLinksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ServiceConfigWebLinks {
    
    private ServiceConfigWebLinksLink1 link1Field;
    
    private ServiceConfigWebLinksLink2 link2Field;
    
    /// <remarks/>
    public ServiceConfigWebLinksLink1 Link1 {
        get {
            return this.link1Field;
        }
        set {
            this.link1Field = value;
        }
    }
    
    /// <remarks/>
    public ServiceConfigWebLinksLink2 Link2 {
        get {
            return this.link2Field;
        }
        set {
            this.link2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ServiceConfigWebLinksLink1 {
    
    private string nameField;
    
    private string regexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string regex {
        get {
            return this.regexField;
        }
        set {
            this.regexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ServiceConfigWebLinksLink2 {
    
    private string nameField;
    
    private string regexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string regex {
        get {
            return this.regexField;
        }
        set {
            this.regexField = value;
        }
    }
}
